name: Java CI

on: [push]

env:
  IMAGE_NAME: authentik
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -P jacoco,coveralls -B verify --file pom.xml -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag image